sudo: required
services:
   - docker

before_install:
   - docker build -t oscarmr/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run oscarmr/react-test npm test -- --coverage

after_success:
   - docker build -t oscarmr/multi-client ./client
   - docker build -t oscarmr/multi-nginx ./nginx
   - docker build -t oscarmr/multi-server ./server
   - docker build -t oscarmr/multi-worker ./worker
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push oscarmr/multi-client
   - docker push oscarmr/multi-nginx
   - docker push oscarmr/multi-server
   - docker push oscarmr/multi-worker
